exclude: assets
default_stages: [pre-commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--float-to-top"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - types-redis
          - types-cachetools
          - types-python-dateutil
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length, "120"]
  - repo: https://github.com/PyCQA/autoflake.git
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-duplicate-keys
        language_version: python3
  - repo: https://github.com/python/black.git
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length, "120", --preview]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.6
    hooks:
      # Fixing automatically things like autoflake, but does something more too
      - id: ruff
        args: [ --fix ]
